# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator01.ui'
#
# Created by: PyQt5 UI code generator 5.15.5
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(530, 645)
        Form.setStyleSheet("background-color: rgb(184, 152, 135);")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(20, 80, 491, 101))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("Background-color: #E7B9A0")
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label.setLineWidth(4)
        self.label.setMidLineWidth(3)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.Button7 = QtWidgets.QPushButton(Form, clicked= lambda: self.press_button('7'))
        self.Button7.setGeometry(QtCore.QRect(35, 200, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button7.setFont(font)
        self.Button7.setStyleSheet("background-color: #E77960 ")
        self.Button7.setDefault(False)
        self.Button7.setFlat(False)
        self.Button7.setObjectName("Button7")
        self.Button8 = QtWidgets.QPushButton(Form, clicked= lambda: self.press_button('8'))
        self.Button8.setGeometry(QtCore.QRect(155, 200, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button8.setFont(font)
        self.Button8.setStyleSheet("background-color: #E77960 ")
        self.Button8.setObjectName("Button8")
        self.Button9 = QtWidgets.QPushButton(Form, clicked= lambda: self.press_button('9'))
        self.Button9.setGeometry(QtCore.QRect(275, 200, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button9.setFont(font)
        self.Button9.setStyleSheet("background-color:#E77960 ")
        self.Button9.setObjectName("Button9")
        self.Button4 = QtWidgets.QPushButton(Form, clicked= lambda: self.press_button('4'))
        self.Button4.setGeometry(QtCore.QRect(35, 280, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button4.setFont(font)
        self.Button4.setStyleSheet("background-color: #E77960 ")
        self.Button4.setObjectName("Button4")
        self.Button6 = QtWidgets.QPushButton(Form, clicked= lambda: self.press_button('6'))
        self.Button6.setGeometry(QtCore.QRect(275, 280, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button6.setFont(font)
        self.Button6.setAutoFillBackground(False)
        self.Button6.setStyleSheet("background-color: #E77960 ")
        self.Button6.setObjectName("Button6")
        self.Button5 = QtWidgets.QPushButton(Form, clicked= lambda: self.press_button('5'))
        self.Button5.setGeometry(QtCore.QRect(155, 280, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button5.setFont(font)
        self.Button5.setStyleSheet("background-color: #E77960 ")
        self.Button5.setObjectName("Button5")
        self.Button1 = QtWidgets.QPushButton(Form, clicked= lambda: self.press_button('1'))
        self.Button1.setGeometry(QtCore.QRect(35, 360, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button1.setFont(font)
        self.Button1.setStyleSheet("background-color: #E77960 ")
        self.Button1.setObjectName("Button1")
        self.Button2 = QtWidgets.QPushButton(Form, clicked= lambda: self.press_button('2'))
        self.Button2.setGeometry(QtCore.QRect(155, 360, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button2.setFont(font)
        self.Button2.setStyleSheet("background-color: #E77960 ")
        self.Button2.setObjectName("Button2")
        self.Button3 = QtWidgets.QPushButton(Form, clicked= lambda: self.press_button('3'))
        self.Button3.setGeometry(QtCore.QRect(275, 360, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button3.setFont(font)
        self.Button3.setStyleSheet("Background-color:#E77960  ")
        self.Button3.setObjectName("Button3")
        self.DivideButton = QtWidgets.QPushButton(Form, clicked= lambda: self.plusminusmultidivide('/'))
        self.DivideButton.setGeometry(QtCore.QRect(415, 210, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DivideButton.setFont(font)
        self.DivideButton.setStyleSheet("Background-color: #E7B9A0")
        self.DivideButton.setObjectName("DivideButton")
        self.MultiplyButton = QtWidgets.QPushButton(Form, clicked= lambda: self.plusminusmultidivide('*'))
        self.MultiplyButton.setGeometry(QtCore.QRect(415, 290, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MultiplyButton.setFont(font)
        self.MultiplyButton.setStyleSheet("Background-color: #E7B9A0")
        self.MultiplyButton.setObjectName("MultiplyButton")
        self.MinusButton = QtWidgets.QPushButton(Form, clicked= lambda: self.plusminusmultidivide('-'))
        self.MinusButton.setGeometry(QtCore.QRect(415, 370, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.MinusButton.setFont(font)
        self.MinusButton.setStyleSheet("Background-color: #E7B9A0")
        self.MinusButton.setObjectName("MinusButton")
        self.PlusButton = QtWidgets.QPushButton(Form, clicked= lambda: self.plusminusmultidivide('+'))
        self.PlusButton.setGeometry(QtCore.QRect(415, 450, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PlusButton.setFont(font)
        self.PlusButton.setStyleSheet("Background-color: #E7B9A0")
        self.PlusButton.setObjectName("PlusButton")
        self.Button0 = QtWidgets.QPushButton(Form, clicked= lambda: self.press_button('0'))
        self.Button0.setGeometry(QtCore.QRect(155, 440, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Button0.setFont(font)
        self.Button0.setStyleSheet("background-color: #E77960 ")
        self.Button0.setObjectName("Button0")
        self.EqualButton = QtWidgets.QPushButton(Form, clicked= lambda: self.mathequal_button())
        self.EqualButton.setGeometry(QtCore.QRect(35, 440, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.EqualButton.setFont(font)
        self.EqualButton.setStyleSheet("Background-color: #E7B9A0")
        self.EqualButton.setObjectName("EqualButton")
        self.DotButton = QtWidgets.QPushButton(Form, clicked= lambda: self.dot_button())
        self.DotButton.setGeometry(QtCore.QRect(275, 440, 111, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.DotButton.setFont(font)
        self.DotButton.setStyleSheet("Background-color: #E7B9A0")
        self.DotButton.setObjectName("DotButton")
        self.CEButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_button('CE'))
        self.CEButton.setGeometry(QtCore.QRect(34, 520, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CEButton.setFont(font)
        self.CEButton.setStyleSheet("Background-color: #E7B9A0")
        self.CEButton.setObjectName("CEButton")
        self.CButton = QtWidgets.QPushButton(Form, clicked= lambda: self.press_button('C'))
        self.CButton.setGeometry(QtCore.QRect(224, 520, 171, 81))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.CButton.setFont(font)
        self.CButton.setStyleSheet("Background-color: #E7B9A0")
        self.CButton.setObjectName("CButton")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(30, 19, 471, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        font.setBold(False)
        font.setWeight(50)
        self.label_2.setFont(font)
        self.label_2.setTabletTracking(False)
        self.label_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.label_2.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.label_2.setStyleSheet("Background-color: #F0A780")
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.label_2.setLineWidth(2)
        self.label_2.setMidLineWidth(1)
        self.label_2.setTextFormat(QtCore.Qt.PlainText)
        self.label_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.Del_Button = QtWidgets.QPushButton(Form, clicked= lambda: self.del_button())
        self.Del_Button.setGeometry(QtCore.QRect(415, 527, 81, 71))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.Del_Button.setFont(font)
        self.Del_Button.setStyleSheet("Background-color: #E7B9A0")
        self.Del_Button.setObjectName("Del_Button")


        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)



    def press_button(self, pressed):
        display_2 = self.label_2.text()
        if pressed == 'C':
            self.label.setText('0')
            self.label_2.setText('0')
        elif pressed == 'CE':
            self.label.setText('0')
        elif display_2 == '0-':
            self.label.setText('-' + str(pressed))
            self.label_2.setText('0')

            
        else:
            if self.label.text() == '0':
                self.label.setText(pressed)
            else:
                self.label.setText(str(self.label.text()) + str(pressed))


    def dot_button(self):
        display = self.label.text()
        if '.' in display:
            pass

        else:
            self.label.setText(str(display) + '.')


    def mathequal_button(self):
        #try
        '''self.numb2 = [self.label.text()]
        self.numb1 = [self.label_2.text() + self.label.text()]
        string111 = ''.join(self.numb1) + ''.join(self.numb2)
        self.label_2.setText(string111)
        ans = eval(string111)
        self.label.setText(str(ans))
        self.numb1 = [str(ans)]
        self.numb2 = []'''

        if self.label_2.text() == "0":
            display = self.label.text()
        else:
            self.label_2.setText(str(self.label_2.text()) + str(self.label.text()))
            display = self.label_2.text()
        try:
            answer = eval(display)
            count = 20
            if len(str(answer)) <= count:
                self.label.setText(str(answer))
                self.label_2.setText("0")
            else:
                if "." in str(answer):
                    while len(str(answer)) > count and count > 0:
                        answer = round(answer, count)
                        count -= 1
                    self.label.setText(str(answer))
                    if len(str(answer)) > count:
                        finalanswer = str(answer)[0] + "." + str(answer)[1] + '*10**' + str(len(str(answer))-3)
                        self.label.setText(finalanswer)
                else:
                    finalanswer = str(answer)[0] + "." + str(answer)[1] + '*10**' + str(len(str(answer))-1)
                    self.label.setText(str(finalanswer))
                self.label_2.setText("0")
        except:
            self.label.setText("ERROR")
            self.label_2.setText("0")


    def plusminusmultidivide(self, pressed):
        if self.label.text() == '0' and self.label_2.text()[-1].isnumeric() == False:
            self.label.setText('0')
            self.label_2.setText(str(self.label_2.text()[:-1]) + str(pressed))
        elif self.label_2.text() == '0':
            self.label_2.setText(str(self.label.text()) + str(pressed))
            self.label.setText('0')
        else:
            self.label_2.setText(str(self.label_2.text()) + str(self.label.text()) + str(pressed))
            self.label.setText('0')

    def del_button(self):
        display = self.label.text()
        display = display[:-1]
        self.label.setText(str(display))
        print(str(display))


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "0"))
        self.Button7.setText(_translate("Form", "7"))
        self.Button8.setText(_translate("Form", "8"))
        self.Button9.setText(_translate("Form", "9"))
        self.Button4.setText(_translate("Form", "4"))
        self.Button6.setText(_translate("Form", "6"))
        self.Button5.setText(_translate("Form", "5"))
        self.Button1.setText(_translate("Form", "1"))
        self.Button2.setText(_translate("Form", "2"))
        self.Button3.setText(_translate("Form", "3"))
        self.DivideButton.setText(_translate("Form", "/"))
        self.MultiplyButton.setText(_translate("Form", "*"))
        self.MinusButton.setText(_translate("Form", "-"))
        self.PlusButton.setText(_translate("Form", "+"))
        self.Button0.setText(_translate("Form", "0"))
        self.EqualButton.setText(_translate("Form", "="))
        self.DotButton.setText(_translate("Form", "."))
        self.CEButton.setText(_translate("Form", "CE"))
        self.CButton.setText(_translate("Form", "C"))
        self.label_2.setText(_translate("Form", "0"))
        self.Del_Button.setText(_translate("Form", "DEL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
